DROP DATABASE IF EXISTS ssafit_a;
CREATE DATABASE ssafit_a DEFAULT CHARACTER SET utf8mb4;

USE ssafit_a;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `video`;
DROP TABLE IF EXISTS `saved_video`;

CREATE TABLE `users` (
    `no` INT AUTO_INCREMENT,
    `user_id` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY(`no`)
);

CREATE TABLE `video` (
    `no` INT AUTO_INCREMENT,
    `title` VARCHAR(50) NOT NULL,
    `part` VARCHAR(100) NOT NULL,
    `url` VARCHAR(100) NOT NULL,
    PRIMARY KEY(`no`)
);

CREATE TABLE `saved_video` (
    `no` INT AUTO_INCREMENT,
    `user_no` INT NOT NULL,
    `video_no` INT NOT NULL,
    PRIMARY KEY (`no`),
    FOREIGN KEY (`user_no`) REFERENCES `users`(`no`) ON DELETE CASCADE,
    FOREIGN KEY (`video_no`) REFERENCES `video`(`no`) ON DELETE CASCADE
);

DESC users;
DESC video;
DESC saved_video;

SELECT * FROM users;
SELECT * FROM video;
SELECT * FROM saved_video;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
